### ISSUE TITLE
Esse repo vão ter as respostas também?

### ISSUE THREAD

**Issue by condini-mastheus** [rubenmarcus/120-perguntas-frontend#1]
As perguntas são bem da hora, principalmente as perguntas de `senior` e `expert`. 

As respostas vão estar aqui também como é no https://github.com/sudheerj/vuejs-interview-questions#what-is-vuejs citado no READ.ME?

**Comment by rubenmarcus** [comment]
@condini-mastheus  sim. Eu no momento to no final de entrega de TCC da faculdade, e terminando de montar minha palestra ai nao tive tempo de por as respostas aqui, mas a ideia e ir colocando em Dezembro e acho que ate Fevereiro no maximo temos todas as respostas aqui.

**Comment by condini-mastheus** [comment]
@rubenmarcus posso tentar preencher algumas, o que voce acha?

**Comment by rubenmarcus** [comment]
@condini-mastheus acho bacana. Faz um P/R
